<img style="float: right; margin: 0px 0px 15px 15px;" src="https://facturedo.cl/wp-content/uploads/2019/10/Chile-pequenas-inversiones.png" width="600px" height="100px" />


# PROYECTO IIl.
## Acompañamiento para inversiones seguras.
### Modelo de ahorro.

 + FRANCISCO JAVIER DIAZ ESQUIVEL IC727603
 + ERIK DANIEL COTA VILLA IC727872

## ANTECEDENTES


### Capitalización por interés simple
Este tipo de interés se calcula <font color=red>única y exclusivamente sobre la cantidad original que se invirtió</font>. Como consecuencia, el interés generado no forma parte del dinero que se invierte, es decir, los <font color=blue>intereses no ganan intereses</font>.

Suponga que se tiene un capital inicial $C_0$ y se invierte a un plazo de $k$ periodos (pueden ser meses, trimestres, semestres, años...) a una tasa de **interés simple** por periodo $i$. Al final del primer periodo, el capital $C_1$ que se obtiene es:

$$C_1=C_0+iC_0=C_0(1+i).$$

De la misma manera, como el interés solo se calcula sobre el capital inicial, al final del segundo periodo, el capital $C_2$ que se obtiene es:

$$C_2=C_1+iC_0=C_0+iC_0+iC_0=C_0(1+2i).$$

Así, al final del $k-$ésimo periodo, el capital $C_k$ que se obtiene es:

$$C_k=C_{k-1}+iC_0=C_0+kiC_0=C_0(1+ki).$$



### Modelo que representa el problema.

Una empresa financiera desea facilitarle a sus clientes la manera de darle seguimiento a sus inversiones y ahorros. Para esto, realizan un programa el cual funciona como una herramienta para visualizar los abonos, intereses, balance y meses restantes para llegar al capital objetivo; de sus movimientos bancarios (inversiones). Esto con ayuda de Jupyter.​


El caso presentado a continuación se trata de una inversión Plan Flexible en BBVA Bancomer. Esta tiene los siguientes parámetros:​

Monto mínimo de inversión de $25,000 MXN​

La tasa de interés (simple) que paga es 0.3% mensual​

Sus plazos son de 182 y 364 días con renovación.​

​

*Cabe destacar que el cliente busca alcanzar $27,000 MXN*



Primero definimos los parámetros del tipo de inversión y caso particular:​

C0=25,000  (Capital inicial)                                                                  i=.003 (Tasa de interés mensual)​

meta_1=27,000 (Capital meta)​

​


Posteriormente definimos los valores  (algebraicos) del periodo k  (numero de meses) para tabular y graficar:

$k=np.ceil(meta_1/C0-1)/i$


$Ck=round((C0*(1+i)**k,2)$



Formulamos, para después definir también los valores algebraicos de Meses restantes, índice, Balance y Abono para tabular:
​
* indice=np.arrange(0, len(fecha)):Fechas 
* A=C0+((i*C0)*índice):Balance
* M=k-indice: Meses restantes
* M=k-indice: Meses restantes
* a=i*C0: Abono
* fecha=pd.date_range(“2020-12-03”, periods=k, freq=“MS”):Para indice
​

Establecemos los parámetros de la tabla con los valores anteriormente definidos, asignándole los nombres a las columnas.


Finalmente, creamos una grafica interactiva para representar los meses pasados y el capital obtenido deseado. Esto definiendo y estableciendo ciertos valores y funciones.

In [16]:
import pandas as pd
from scipy. integrate import solve_ivp
import sympy as sym
from ipywidgets import *
import matplotlib.pyplot as plt
import numpy as np

In [18]:
meta_1=27000 # Capital meta
C0=25000 # Capital inicial
i=.003 # Tasa de interes mensual

In [19]:
k=np.ceil((meta_1/C0-1)/i)  # Numero de meses
Ck=round(C0*(1+i)**k,2)  # Capital meta para grafica

In [20]:
fecha=pd.date_range("2020-12-03", periods=k, freq="MS")
indice=np.arange(0, len(fecha)) # Fechas
M=k-indice # Meses restantes para alcanzar la meta
A=C0+((i*c0)*indice) # Balance
a=i*c0 # Abono

In [21]:
tabla=pd.DataFrame(index=fecha, columns=["Abono", "Balance", "Meses restantes"]) # Meses nec. para alcanzar la meta
tabla["Meses restantes"]=M                                       
tabla["Balance"]=A
tabla["Abono"]=a
tabla

            Abono  Balance  Meses restantes
2021-01-01   75.0  25000.0             27.0
2021-02-01   75.0  25075.0             26.0
2021-03-01   75.0  25150.0             25.0
2021-04-01   75.0  25225.0             24.0
2021-05-01   75.0  25300.0             23.0
2021-06-01   75.0  25375.0             22.0
2021-07-01   75.0  25450.0             21.0
2021-08-01   75.0  25525.0             20.0
2021-09-01   75.0  25600.0             19.0
2021-10-01   75.0  25675.0             18.0
2021-11-01   75.0  25750.0             17.0
2021-12-01   75.0  25825.0             16.0
2022-01-01   75.0  25900.0             15.0
2022-02-01   75.0  25975.0             14.0
2022-03-01   75.0  26050.0             13.0
2022-04-01   75.0  26125.0             12.0
2022-05-01   75.0  26200.0             11.0
2022-06-01   75.0  26275.0             10.0
2022-07-01   75.0  26350.0              9.0
2022-08-01   75.0  26425.0              8.0
2022-09-01   75.0  26500.0              7.0
2022-10-01   75.0  26575.0              6.0
2022-11-01   75.0  26650.0              5.0
2022-12-01   75.0  26725.0              4.0
2023-01-01   75.0  26800.0              3.0
2023-02-01   75.0  26875.0              2.0
2023-03-01   75.0  26950.0              1.0

In [22]:
def Ccontinua(C0, r, meta):
    t=np.log(meta/C0)/r
    
    #periodos=np.linspace(0, t, )
    def dC(t, C):
        return r*C
    sol=solve_ivp(dC, (0,t), [C0], max_step=.01)

    plt.plot(sol.t, sol.y[0,:])
    plt.plot([0,t],[meta, meta], "--k")
    plt.xlabel("meses")
    plt.grid()
    
interact_manual(Ccontinua, C0=fixed(c0),r=fixed(np.log(1+i)),meta=(c0,c0*2,i*c0))

interactive(children=(FloatSlider(value=37450.0, description='meta', max=50000.0, min=25000.0, step=75.0), But…

In [23]:
print("El tiempo necesario para alcanzar", meta_1, "MXN","son",k, "meses", ". El capital total obtenido es de", round(C0*(1+k*i),2), "pesos.",sep=" ")

El tiempo necesario para alcanzar 27000 MXN son 27.0 meses . El capital total obtenido es de 27025.0 pesos.

### REPRESENTACIÓN DE RESULTADOS:

En las tablas se identifica la fecha, abono, balance y meses restantes para llegar al capital​

En la grafica interactiva los meses y el capital obtenido son representados visualmente​

Y  por ultimo se imprime en la pantalla el tiempo necesario para llegar al capital deseado y el capital total obtenido. Todo esto de manera textual​

​

### BIBLIOGRAFÍA

​

Viadurri, H. (2013). Ingeniería económica básica. Diciembre 2, 2020, de Biblioteca Dr. Jorge Villalobos Padilla Sitio web: https://biblio.iteso.mx/​

​

Da Silva, M. (2010). Generador de presentaciones multimedia. Diciembre 1, 2020, de Slideshare Sitio web: https://es.slideshare.net/MeireComputacion/power-point-pautas-para-una-buen-trabajo